---
title: "group_miRNA_sequences"
author: "mz"
date: "16 1 2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}

require(tictoc)


```

```{r}


mainDir = getwd()
inputFolder = "../input/MIRNAs"
outputFolder = "../output/"
whereTo1 = paste0(file.path(outputFolder), "/", "miRNA_5p-3p_grouping.txt")
whereTo2 = paste0(file.path(outputFolder), "/", "isomiRs.txt")

myFiles = list.files(path = file.path(mainDir, inputFolder), pattern = "\\.txt$")
dir.create(file.path(outputFolder), showWarnings = FALSE)
file.create(whereTo1)
file.create(whereTo2)
# colnames output 1
temp = cbind("Name miRNA", "miRNA_5p", "miRNA_3p",
             "miRNA length_5p", "miRNA length_3p", "miRNA counts_5p", "miRNA counts_3p")
write.table(temp, file = whereTo1, 
            append = FALSE, 
            sep = "\t",
            row.names = FALSE,
            col.names = FALSE,
            quote = FALSE)
# colnames output 2
temp = cbind("miRNA_ID", "miRNA_sequence", "length", "count")
write.table(temp, file = whereTo2, 
            append = FALSE, 
            sep = "\t",
            row.names = FALSE,
            col.names = FALSE,
            quote = FALSE)

tic()

for (i in 1:length(myFiles)) {
  # print(i)
  tmp = readLines(paste0(file.path(mainDir, inputFolder), "/", myFiles[i]))
  longString = tmp[3]
  nchar(longString)
  subString1 = gsub("\\.", "", strsplit(tmp[5], " ")[[1]][1])
  subString1.len = strsplit(strsplit(tmp[5], " ")[[1]][3], "l=")[[1]][2]
  subString1.cnt = strsplit(strsplit(tmp[5], " ")[[1]][4], "a=")[[1]][2]
  subString2 = gsub("\\.", "", strsplit(tmp[6], " ")[[1]][1])
  subString2.len = strsplit(strsplit(tmp[6], " ")[[1]][3], "l=")[[1]][2]
  subString2.cnt = strsplit(strsplit(tmp[6], " ")[[1]][4], "a=")[[1]][2]
  nchar(subString1)
  nchar(subString2)
  
  grepl(subString1, longString)
  subString1Start = regexpr(subString1, longString)[1]
  
  grepl(subString2, longString)
  subString2Start = regexpr(subString2, longString)[1]
  
  miRNA_5p = NULL
  miRNA_3p = NULL
  
  if (subString1Start < subString2Start) {
    miRNA_5p = subString1
    miRNA_3p = subString2
    miRNA_length_5p = subString1.len
    miRNA_counts_5p = subString1.cnt
    miRNA_length_3p = subString2.len
    miRNA_counts_3p = subString2.cnt
  } else {
    miRNA_3p = subString1
    miRNA_5p = subString2
    miRNA_length_3p = subString1.len
    miRNA_counts_3p = subString1.cnt
    miRNA_length_5p = subString2.len
    miRNA_counts_5p = subString2.cnt
  }
  
  Name.miRNA = gsub("\\.txt", "", myFiles[i])
  # only if you want to remove e.g. _Y post Cluster_631
  Name.miRNA = paste(strsplit(Name.miRNA, "_")[[1]][1], strsplit(Name.miRNA, "_")[[1]][2], sep = "_")
  
  
  temp = cbind(Name.miRNA, miRNA_5p, miRNA_3p, miRNA_length_5p, miRNA_counts_5p, miRNA_length_3p, miRNA_counts_3p)
  
  write.table(temp, file = whereTo1, 
              append = TRUE, 
              sep = "\t",
              row.names = FALSE,
              col.names = FALSE,
              quote = FALSE)
  
  additional.info.from = which(tmp == "")[2] + 1
  additional.info.to = which(tmp == "")[3] - 1
  cnt = 0
  for (j in additional.info.from:additional.info.to) {
    cnt = cnt + 1
    # print (tmp[j])
    miRNA.ID.addon = paste0(Name.miRNA, ".", cnt)
    subString.addon = gsub("\\.", "", strsplit(tmp[j], " ")[[1]][1])
    subString.addon = gsub("<", "", subString.addon)
    subString.addon = gsub(">", "", subString.addon)
    subString.addon.len = strsplit(strsplit(tmp[j], " ")[[1]][2], "l=")[[1]][2]
    subString.addon.cnt = strsplit(strsplit(tmp[j], " ")[[1]][3], "a=")[[1]][2]
    temp = cbind(miRNA.ID.addon, subString.addon, subString.addon.len, subString.addon.cnt)
    write.table(temp, file = whereTo2, 
                append = TRUE, 
                sep = "\t",
                row.names = FALSE,
                col.names = FALSE,
                quote = FALSE)
  }
  # print(cnt)
  
}

print("Done in: ")
toc()

sessionInfo()

```

